// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tokens/": {
            "post": {
                "description": "Refreshes access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "RefreshTokens",
                "parameters": [
                    {
                        "description": "access and refresh tokens",
                        "name": "tokens",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RefreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.RefreshErrResponse"
                        }
                    }
                }
            }
        },
        "/tokens/{user_id}": {
            "get": {
                "description": "Generates access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "GetTokens",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.GenErrResponse": {
            "type": "object",
            "properties": {
                "Error": {
                    "type": "string"
                }
            }
        },
        "handlers.GenResponse": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "AccessTokenExpiresAt": {
                    "type": "string"
                },
                "RefreshToken": {
                    "type": "string"
                },
                "RefreshTokenExpiresAt": {
                    "type": "string"
                }
            }
        },
        "handlers.RefreshErrResponse": {
            "type": "object",
            "properties": {
                "Error": {
                    "type": "string"
                }
            }
        },
        "handlers.RefreshResponse": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "AccessTokenExpiresAt": {
                    "type": "string"
                },
                "RefreshToken": {
                    "type": "string"
                },
                "RefreshTokenExpiresAt": {
                    "type": "string"
                }
            }
        },
        "handlers.RefreshTokensRequest": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "Base64RefreshToken": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Test task API",
	Description:      "This is a test task",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
