definitions:
  handlers.GenErrResponse:
    properties:
      Error:
        type: string
    type: object
  handlers.GenResponse:
    properties:
      AccessToken:
        type: string
      AccessTokenExpiresAt:
        type: string
      RefreshToken:
        type: string
      RefreshTokenExpiresAt:
        type: string
    type: object
  handlers.RefreshErrResponse:
    properties:
      Error:
        type: string
    type: object
  handlers.RefreshResponse:
    properties:
      AccessToken:
        type: string
      AccessTokenExpiresAt:
        type: string
      RefreshToken:
        type: string
      RefreshTokenExpiresAt:
        type: string
    type: object
  handlers.RefreshTokensRequest:
    properties:
      AccessToken:
        type: string
      Base64RefreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /tokens/:
    post:
      consumes:
      - application/json
      description: Refreshes access and refresh tokens
      parameters:
      - description: access and refresh tokens
        in: body
        name: tokens
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshTokensRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RefreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.RefreshErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RefreshErrResponse'
      summary: RefreshTokens
      tags:
      - Tokens
  /tokens/{user_id}:
    get:
      consumes:
      - application/json
      description: Generates access and refresh tokens
      parameters:
      - description: user_id
        in: path
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenErrResponse'
      summary: GetTokens
      tags:
      - Tokens
swagger: "2.0"
